apiVersion: 1
datasources:
  - name: Benchmark
    type: postgres
    uid: benchpg
    url: postgres:5432
    user: bench
    jsonData:
      database: bench
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: bench
    isDefault: true
